builds:
  - id: containerssh-agent
    binary: "containerssh-agent"
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    hooks:
      pre:
        - go generate
        - go test ./...
archives:
  - builds:
      - containerssh-agent
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - vendor: ContainerSSH
    homepage: https://containerssh.io
    maintainer: Janos Pasztor <handshake@containerssh.io>
    description: The guest agent for ContainerSSH, an SSH server that launches containers on demand.
    license: MIT
    package_name: containerssh-agent
    builds:
      - containerssh-agent
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    rpm:
      signature:
        key_file: /var/secrets/signing.gpg
    deb:
      signature:
        key_file: /var/secrets/signing.gpg
    apk:
      signature:
        key_file: /var/secrets/signing.gpg
dockers:
  - image_templates:
      - "containerssh/agent:latest"
      - "containerssh/agent:{{ .Tag }}"
      - "quay.io/containerssh/agent:latest"
      - "quay.io/containerssh/agent:{{ .Tag }}"
    dockerfile: Dockerfile
source:
  enabled: true
  name_template: 'containerssh-agent-{{ .Version }}-source'
signs:
  - id: sign
    artifacts: all
dist: build
release:
  github:
    owner: containerssh
    name: agent
  prerelease: auto
  extra_files:
    - glob: LICENSE.md
